# Generated by Django 4.2.2 on 2023-07-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_location_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
